### ISSUE TITLE
Is it possible to use some emulated device (AVD or iOS) to test the features of the Pedometer?

### ISSUE THREAD

**Issue by carlosdelfino** [EddyVerbruggen/nativescript-pedometer#2]
I am doing the plugin tests, and I want to implement it in my application, however I do not have a device with the necessary features to the Pedometer.

**Comment by EddyVerbruggen** [comment]
You better poke into the vast knowledge of Google for that. Here ya go: [iOS](https://www.google.nl/search?q=ios+pedometer+simulator&oq=ios+pedometer+simulator&aqs=chrome..69i57.4784j0j4&sourceid=chrome&ie=UTF-8), [Android](https://www.google.nl/search?q=ios+pedometer+simulator&oq=ios+pedometer+simulator&aqs=chrome..69i57.4784j0j4&sourceid=chrome&ie=UTF-8#q=android+pedometer+emulator).
