### ISSUE TITLE
isStepCountingAvailable resolve false

### ISSUE THREAD

**Issue by gabetocci** [EddyVerbruggen/nativescript-pedometer#5]
Not sure if this should be an issue, or if it is my dev environment. 
The following code always displays "No":
```
pedometer.isStepCountingAvailable().then((avail) => {
  alert(avail ? "Yes" : "No");
});
```
I am using android emulator with lollipop. If this is the cause, any idea how to test it or mock it? If not, any troubleshooting or debugging steps would be greatly appreciated.

Also, I'm using Nativescript3, angular, and typescript.

**Comment by EddyVerbruggen** [comment]
No idea - Google if there's a way to enable the step counter on an Android sim. I've used a real device during dev.

**Comment by gabetocci** [comment]
yup, works on physical device. thanks
