### ISSUE TITLE
Android onUpdate fromDate not being used

### ISSUE THREAD

**Issue by Nicholas1490** [EddyVerbruggen/nativescript-pedometer#8]
Hi,

I have been playing around with the plugin and it works great on IOS. 
However, on android the onUpdate does not take the fromDate parameter that I supplied. 
It uses the current time instead. 
Any help or guidance will be appreciated. Thanks.

Code: 
```
pedometer.startUpdates({
            fromDate: new Date(2018, 4, 1, 0, 0, 0), // optional, default: now
            onUpdate: result => {
                // see the table below
                console.log(`Pedometer update: ${JSON.stringify(result)}`);
            }
        }).then(() => {
            console.log("Pedometer updates started.");
        }, err => {
            console.log("Error: " + err);
        });
```

IOS Results: 
```
Pedometer update: {"startDate":"2018-05-01T04:00:00.000Z","endDate":"2018-05-03T16:13:28.380Z","steps":194,"distance":147.91999999999462,"floorsAscended":null,"floorsDescended":null,"currentPace":null,"currentCadence":null,"averageActivePace":0}
```

Android Results:
```
Pedometer update: {"startDate":"2018-05-03T16:05:00.498Z","endDate":"2018-05-03T16:05:00.582Z","steps":0}
```

Environment: 
✔ Component nativescript has 4.0.0 version and is up to date.
✔ Component tns-core-modules has 4.0.0 version and is up to date.
✔ Component tns-android has 4.0.1 version and is up to date.
✔ Component tns-ios has 4.0.1 version and is up to date.

IOS Devices:
IPhone 5s - 11.2.6

Android Devices: 
One Plus 5T - Oreo 8.1
One Plus One - Marshmellow 6.0

**Comment by Nicholas1490** [comment]
I was able to get the fromDate to be used by changing a line of code in the plugin.

pedometer.android.js
line 65:
```
_this.startTimestamp = Date().getTime();
```
to
```
_this.startTimestamp = arg.fromDate.getTime() || Date().getTime();
```

However this still doesn't resolve my issue. My steps return as 0.
The steps count is updated but if I close the app and reopen it starts back at 0.
It should be the old steps + new steps within the date range.

I commented out another line 
77 in pedometer.android.js
```
steps = steps - that_1.startSteps;
```

Yes I get my steps and they are retained but I'm pretty sure its an inaccurate count. 
I say this because I changed the fromDate from new Date(2018, 4, 1, 0, 0, 0) to new Date(2018, 3, 15, 0, 0, 0) (15 days ago and I still get the same count). 
I tested a step count for today only and the count is still the same number and it should be a different step count.
My Google Fit app says different.

**Comment by Mxtremeg** [comment]
Hi all,

I am having the exact same issue as the user above. 

Any help ?

**Comment by jorgeartigas** [comment]
same issue, any updates?

**Comment by EddyVerbruggen** [comment]
Unfortunately Android doesn't offer history when listening to sensor updates (iOS does). So this needs to be done manually in your code. But I'll attempt to make the plugin do it for you.

**Comment by EddyVerbruggen** [comment]
Yeah I was afraid of this. Android doesn't offer a way to get hisoric data through the sensor API (only realtime data). But if you need history, I have this:             console.log("Note that unlike iOS, Android doesn't support historic step data.

AFAIK history can only be queried through Google Fit, for which I also have a free plugin: https://github.com/EddyVerbruggen/nativescript-health-data/tree/cb852903bbf8fbad7d63b6c1df799a97014746d1#query

I update the code and readme to reflect these learnings.
